const KEY='clcf_v1_data';
const seed={companies:[],activeCompany:null,accounts:[],vouchers:[],ufv:[],fx:[]};
let data=load(); let currentPage='dashboard';
function load(){try{return {...seed,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch(e){return {...seed}}}
function save(){localStorage.setItem(KEY,JSON.stringify(data))}
const $=s=>document.querySelector(s);
function money(n){return new Intl.NumberFormat('es-BO',{minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(n||0))}
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function active(){return data.companies.find(c=>c.id===data.activeCompany)}
function showApp(){ $('#loginView').classList.add('hidden'); $('#appView').classList.remove('hidden'); render(); }
function render(){const c=active(); $('#sideCompany').textContent=c?c.name:'Sin empresa';$('#sidePeriod').textContent=c?`Gestión ${c.period}`:'Crea o selecciona una empresa';$('#topPeriod').textContent=c?`Gestión ${c.period}`:'Sin gestión';document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.page===currentPage));const titles={dashboard:'Dashboard',accounts:'Plan de cuentas',vouchers:'Comprobantes',journal:'Libro Diario',ledger:'Libro Mayor',trial:'Balance de comprobación',adjustments:'Ajustes',statements:'Estados financieros',notes:'Notas a los estados financieros',banks:'Bancos',inventory:'Inventarios',assets:'Activos fijos',intangibles:'Intangibles',receivables:'Cuentas por cobrar',payables:'Cuentas por pagar',standards:'Normativa contable',parameters:'UFV y tipos de cambio',companies:'Empresas y gestiones',reports:'Reportes'};$('#pageTitle').textContent=titles[currentPage]||'Dashboard';
const fn=pages[currentPage]||pages.dashboard; $('#content').innerHTML=fn(); attachPageEvents();}
function go(p){currentPage=p;$('#sidebar').classList.remove('open');render()}
function dashboard(){const c=active();const totalD=data.vouchers.filter(v=>!c||v.companyId===c.id).reduce((a,v)=>a+Number(v.debit||0),0);const totalH=data.vouchers.filter(v=>!c||v.companyId===c.id).reduce((a,v)=>a+Number(v.credit||0),0);return `<div class="welcome"><div><h2>${c?'Bienvenido a CL&CF':'Bienvenido'}</h2><div class="muted">${c?esc(c.name):'Crea tu primera empresa para comenzar la gestión contable.'}</div></div><button class="btn primary" data-action="new-voucher">+ Nuevo comprobante</button></div><div class="cards"><div class="card metric"><div class="label">Activos</div><div class="value">Bs 0,00</div><div class="hint">Se alimentará desde las cuentas</div></div><div class="card metric"><div class="label">Pasivos</div><div class="value">Bs 0,00</div><div class="hint">Control contable</div></div><div class="card metric"><div class="label">Patrimonio</div><div class="value">Bs 0,00</div><div class="hint">Gestión ${c?.period||'—'}</div></div><div class="card metric"><div class="label">Debe registrado</div><div class="value">Bs ${money(totalD)}</div><div class="hint">Comprobantes V1</div></div><div class="card metric"><div class="label">Haber registrado</div><div class="value">Bs ${money(totalH)}</div><div class="hint">Comprobantes V1</div></div></div><div class="section"><div class="section-head"><h3>Acciones rápidas</h3></div><div class="quick-grid"><button class="quick" data-go="accounts">▤<strong>Plan de cuentas</strong><span>Importar o administrar cuentas.</span></button><button class="quick" data-action="new-company">＋<strong>Crear empresa</strong><span>Registra los datos de una nueva empresa.</span></button><button class="quick" data-action="new-voucher">✎<strong>Nuevo comprobante</strong><span>Prepara tu registro Debe / Haber.</span></button><button class="quick" data-go="parameters">◉<strong>UFV y tipos de cambio</strong><span>Parámetros históricos por fecha.</span></button></div></div><div class="section"><div class="section-head"><h3>Estado de la V1</h3></div><div class="info-grid"><div class="info-box"><h4>Multiempresa</h4><p>${data.companies.length} empresa(s) registrada(s).</p></div><div class="info-box"><h4>Plan de cuentas</h4><p>${data.accounts.length} cuenta(s) cargada(s).</p></div><div class="info-box"><h4>Comprobantes</h4><p>${data.vouchers.length} comprobante(s) de prueba.</p></div></div></div>`}
function companies(){return `<div class="section-head"><div><h3>Empresas y gestiones</h3><div class="muted">Cada empresa mantiene sus datos y periodo de trabajo.</div></div><button class="btn primary" data-action="new-company">+ Crear empresa</button></div><div class="company-grid">${data.companies.length?data.companies.map(c=>`<div class="company-card"><span class="tag">${esc(c.type)}</span><h3>${esc(c.name)}</h3><p class="muted">NIT: ${esc(c.nit||'—')} · Gestión ${esc(c.period)}</p><p class="muted">${esc(c.address||'Sin dirección')} · ${esc(c.phone||'Sin teléfono')}</p><div class="toolbar-left"><button class="btn ${data.activeCompany===c.id?'secondary':'primary'}" data-company="${c.id}">${data.activeCompany===c.id?'Empresa activa':'Ingresar'}</button><button class="btn ghost" data-company-edit="${c.id}">Editar</button></div></div>`).join(''):`<div class="panel"><div class="empty">Todavía no hay empresas. Crea la primera para comenzar.</div></div>`}</div>`}
function accounts(){return `<div class="notice">El plan de cuentas será independiente por empresa. En esta V1 puedes importar un archivo CSV con las columnas: <b>Código, Cuenta, Tipo, Nivel, Cuenta padre</b>.</div><div class="panel"><div class="toolbar"><div class="toolbar-left"><input class="search" id="accountSearch" placeholder="Buscar código o cuenta..."></div><div class="toolbar-right"><button class="btn secondary" data-action="import-accounts">↑ Importar CSV</button><button class="btn ghost" data-action="export-accounts">↓ Exportar CSV</button><button class="btn primary" data-action="new-account">+ Nueva cuenta</button></div></div><div class="table-wrap"><table><thead><tr><th>Código</th><th>Cuenta</th><th>Tipo</th><th>Nivel</th><th>Cuenta padre</th></tr></thead><tbody id="accountsBody">${accountRows(data.accounts)}</tbody></table></div></div>`}
function accountRows(arr){if(!arr.length)return `<tr><td colspan="5"><div class="empty">No hay cuentas cargadas para esta V1.</div></td></tr>`;return arr.map(a=>`<tr><td><b>${esc(a.code)}</b></td><td>${esc(a.name)}</td><td>${esc(a.type)}</td><td>${esc(a.level||'')}</td><td>${esc(a.parent||'')}</td></tr>`).join('')}
function vouchers(){const vs=data.vouchers.filter(v=>!active()||v.companyId===active().id);return `<div class="panel"><div class="toolbar"><div class="toolbar-left"><input class="search" id="voucherSearch" placeholder="Buscar comprobante..."></div><div class="toolbar-right"><button class="btn primary" data-action="new-voucher">+ Nuevo comprobante</button></div></div><div class="table-wrap"><table><thead><tr><th>Nº</th><th>Fecha</th><th>Concepto</th><th>Debe</th><th>Haber</th><th>Estado</th></tr></thead><tbody>${vs.length?vs.map(v=>`<tr><td>${esc(v.number)}</td><td>${esc(v.date)}</td><td>${esc(v.concept)}</td><td>Bs ${money(v.debit)}</td><td>Bs ${money(v.credit)}</td><td><span class="tag">${v.debit===v.credit?'Cuadrado':'Revisar'}</span></td></tr>`).join(''):`<tr><td colspan="6"><div class="empty">No existen comprobantes registrados.</div></td></tr>`}</tbody></table></div></div>`}
function generic(title,desc,items){return `<div class="notice">${desc}</div><div class="info-grid">${items.map(x=>`<div class="info-box"><h4>${x[0]}</h4><p>${x[1]}</p></div>`).join('')}</div>`}
function journal(){return generic('Libro Diario','En la siguiente etapa, los comprobantes contabilizados se reflejarán automáticamente aquí.',[['Orden cronológico','Fecha, número y glosa del comprobante.'],['Debe / Haber','Detalle por cuenta y monto.'],['Control','Validación de igualdad Debe = Haber.']])}
function ledger(){return generic('Libro Mayor','Módulo preparado para consultar movimientos agrupados por cuenta.',[['Cuenta','Saldo inicial y movimientos.'],['Débitos','Total de cargos por cuenta.'],['Créditos','Total de abonos por cuenta.']])}
function trial(){return generic('Balance de comprobación','Control previo a los estados financieros.',[['Sumas','Debe y Haber por cuenta.'],['Saldos','Deudor y acreedor.'],['Validación','Detección de diferencias.']])}
function adjustments(){return generic('Ajustes contables','Espacio preparado para ajustes de cierre, UFV, tipo de cambio, depreciaciones y otros.',[['UFV','Actualización según parámetros registrados.'],['Depreciación','Control de activos fijos.'],['Cierre','Ajustes antes de emitir estados.']])}
function statements(){return generic('Estados financieros','La V1 deja preparada la sección para generar reportes a partir del mayor y balance de comprobación.',[['Estado de Situación Financiera','Activo, pasivo y patrimonio.'],['Estado de Resultados','Ingresos, costos y gastos.'],['Flujo de efectivo','Estructura preparada para una siguiente versión.'],['Cambios en patrimonio','Estructura preparada.'],['Notas','Referencias y políticas contables.'],['Impresión','Formato profesional mediante impresión del navegador.']])}
function notes(){return generic('Notas a los estados financieros','Módulo preparado para incorporar políticas contables, desgloses y referencias a NC, NIC y NIIF.',[['Políticas contables','Texto y criterios aplicados.'],['Desgloses','Información complementaria.'],['Normativa','Vinculación documental con estándares.']])}
function modules(name,desc){return generic(name,desc,[['Registro','Estructura base del módulo.'],['Integración contable','Preparado para generar comprobantes automáticamente.'],['Reportes','Preparado para consultas y exportación.']])}
function standards(){const nc=['NC 1','NC 2','NC 3','NC 4','NC 5','NC 6','NC 7','NC 8','NC 9','NC 10','NC 11','NC 12','NC 13','NC 14'];return `<div class="notice">Biblioteca de referencia de la V1. La información normativa detallada se incorporará por estándar y versión, evitando presentar como automatizado aquello que aún no esté parametrizado.</div><div class="section-head"><h3>Normas de Contabilidad Bolivianas</h3></div><div class="checklist">${nc.map(n=>`<div class="check"><b>${n}</b><div class="muted">Disponible para documentación y parametrización.</div></div>`).join('')}</div><div class="section"><div class="info-grid"><div class="info-box"><h4>NIC</h4><p>Biblioteca y referencias para notas y criterios contables.</p></div><div class="info-box"><h4>NIIF</h4><p>Biblioteca y referencias para presentación y revelación.</p></div><div class="info-box"><h4>Control</h4><p>Las reglas automáticas se irán habilitando módulo por módulo.</p></div></div></div>`}
function parameters(){return `<div class="notice">Registra valores por fecha para conservar histórico. En esta V1 los datos se guardan localmente en el navegador.</div><div class="panel"><div class="toolbar"><b>UFV</b><button class="btn primary" data-action="new-ufv">+ Registrar UFV</button></div><div class="table-wrap"><table><thead><tr><th>Fecha</th><th>UFV</th></tr></thead><tbody>${data.ufv.length?data.ufv.map(x=>`<tr><td>${esc(x.date)}</td><td>${money(x.value)}</td></tr>`).join(''):`<tr><td colspan="2"><div class="empty">Sin valores registrados.</div></td></tr>`}</tbody></table></div></div><div class="section panel"><div class="toolbar"><b>Tipos de cambio</b><button class="btn primary" data-action="new-fx">+ Registrar tipo de cambio</button></div><div class="table-wrap"><table><thead><tr><th>Fecha</th><th>Moneda</th><th>Compra</th><th>Venta</th></tr></thead><tbody>${data.fx.length?data.fx.map(x=>`<tr><td>${esc(x.date)}</td><td>${esc(x.currency)}</td><td>${money(x.buy)}</td><td>${money(x.sell)}</td></tr>`).join(''):`<tr><td colspan="4"><div class="empty">Sin tipos de cambio registrados.</div></td></tr>`}</tbody></table></div></div>`}
function reports(){return `<div class="notice">Los reportes de la V1 usan los datos del navegador. Para PDF utiliza <b>Imprimir → Guardar como PDF</b>. La exportación CSV puede abrirse directamente con Excel.</div><div class="info-grid"><div class="info-box"><h4>Plan de cuentas</h4><p>Exporta el plan actual en CSV.</p><button class="btn secondary" data-action="export-accounts">Exportar</button></div><div class="info-box"><h4>Libro Diario</h4><p>Vista preparada para impresión.</p><button class="btn primary" data-action="print">Imprimir</button></div><div class="info-box"><h4>Estados financieros</h4><p>Formato preparado para la siguiente etapa de cálculo automático.</p><button class="btn primary" data-action="print">Imprimir</button></div></div>`}
function pageFallback(){return generic('', 'Módulo base de la V1.',[['Preparado','La estructura queda lista para integrar datos.']])}
const pages={dashboard,accounts,vouchers,journal,ledger,trial,adjustments,statements,notes,standards,parameters,companies,reports,banks:()=>modules('Bancos','Control de cuentas bancarias, movimientos y conciliación.'),inventory:()=>modules('Inventarios','Control de existencias, entradas, salidas y valorización.'),assets:()=>modules('Activos fijos','Altas, bajas, depreciación, revaluación y control por activo.'),intangibles:()=>modules('Intangibles','Control de activos intangibles y amortización.'),receivables:()=>modules('Cuentas por cobrar','Control de clientes, vencimientos y cobranzas.'),payables:()=>modules('Cuentas por pagar','Control de proveedores, vencimientos y pagos.')};
function modal(title,body){$('#modalTitle').textContent=title;$('#modalBody').innerHTML=body;$('#modal').classList.remove('hidden')}
function closeModal(){$('#modal').classList.add('hidden')}
function attachPageEvents(){document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));document.querySelectorAll('[data-company]').forEach(b=>b.onclick=()=>{data.activeCompany=b.dataset.company;save();go('dashboard')});document.querySelectorAll('[data-company-edit]').forEach(b=>b.onclick=()=>editCompany(b.dataset.company));document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>action(b.dataset.action));const s=$('#accountSearch');if(s)s.oninput=()=>$('#accountsBody').innerHTML=accountRows(data.accounts.filter(a=>(a.code+' '+a.name).toLowerCase().includes(s.value.toLowerCase())))}
function action(a){if(a==='new-company')newCompany();if(a==='new-account')newAccount();if(a==='import-accounts')importAccounts();if(a==='export-accounts')exportAccounts();if(a==='new-voucher')newVoucher();if(a==='new-ufv')newUFV();if(a==='new-fx')newFX();if(a==='print')window.print()}
function newCompany(existing={}){modal(existing.id?'Editar empresa':'Crear nueva empresa',`<form id="companyForm"><div class="form-grid"><label>Razón social / Nombre<input name="name" required value="${esc(existing.name||'')}"></label><label>NIT<input name="nit" value="${esc(existing.nit||'')}"></label><label>Tipo de empresa<select name="type"><option>Comercial</option><option>Industrial</option><option>Agrícola</option><option>Minera</option><option>Servicios</option><option>Otra</option></select></label><label>Gestión<input name="period" type="number" min="2000" max="2100" required value="${esc(existing.period||new Date().getFullYear())}"></label><label>Fecha de inicio<input name="start" type="date" value="${esc(existing.start||'')}"></label><label>Fecha de cierre<input name="end" type="date" value="${esc(existing.end||'')}"></label><label>Dirección<input name="address" value="${esc(existing.address||'')}"></label><label>Teléfono<input name="phone" value="${esc(existing.phone||'')}"></label><label>Correo electrónico<input name="email" type="email" value="${esc(existing.email||'')}"></label><label>Página web<input name="web" value="${esc(existing.web||'')}"></label><label class="full-field">Logo (opcional)<input name="logo" type="text" placeholder="En una versión futura se podrá subir el logo de la empresa"></label></div><div class="form-actions"><button type="button" class="btn ghost" id="cancelModal">Cancelar</button><button class="btn primary">Guardar empresa</button></div></form>`);$('#companyForm').querySelector('[name=type]').value=existing.type||'Comercial';$('#cancelModal').onclick=closeModal;$('#companyForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);const c=Object.fromEntries(f.entries());c.id=existing.id||crypto.randomUUID();if(existing.id){const i=data.companies.findIndex(x=>x.id===existing.id);data.companies[i]={...data.companies[i],...c}}else{data.companies.push(c);data.activeCompany=c.id}save();closeModal();go('companies')}}
function editCompany(id){const c=data.companies.find(x=>x.id===id);if(c)newCompany(c)}
function newAccount(){modal('Nueva cuenta',`<form id="accountForm"><div class="form-grid"><label>Código<input name="code" required></label><label>Cuenta<input name="name" required></label><label>Tipo<select name="type"><option>Activo</option><option>Pasivo</option><option>Patrimonio</option><option>Ingreso</option><option>Gasto</option><option>Costo</option></select></label><label>Nivel<input name="level" type="number" min="1" value="1"></label><label class="full-field">Cuenta padre<input name="parent"></label></div><div class="form-actions"><button type="button" class="btn ghost" id="cancelModal">Cancelar</button><button class="btn primary">Guardar</button></div></form>`);$('#cancelModal').onclick=closeModal;$('#accountForm').onsubmit=e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));data.accounts.push(f);save();closeModal();render()}}
function importAccounts(){const inp=document.createElement('input');inp.type='file';inp.accept='.csv,text/csv';inp.onchange=()=>{const file=inp.files[0];if(!file)return;const r=new FileReader();r.onload=()=>{const lines=r.result.split(/\r?\n/).filter(Boolean);const headers=lines.shift().split(',').map(x=>x.trim().toLowerCase());const map={codigo:'code',código:'code',cuenta:'name',tipo:'type',nivel:'level','cuenta padre':'parent'};const rows=lines.map(line=>{const vals=line.split(',');const o={};headers.forEach((h,i)=>{if(map[h])o[map[h]]=vals[i]?.trim()||''});return o}).filter(x=>x.code&&x.name);data.accounts.push(...rows);save();render();alert(`Se importaron ${rows.length} cuentas.`)};r.readAsText(file,'UTF-8')};inp.click()}
function exportAccounts(){const rows=[['Código','Cuenta','Tipo','Nivel','Cuenta padre'],...data.accounts.map(a=>[a.code,a.name,a.type,a.level||'',a.parent||''])];const csv=rows.map(r=>r.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(',')).join('\n');const blob=new Blob([csv],{type:'text/csv;charset=utf-8;'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='CLCF_Plan_de_Cuentas.csv';a.click();URL.revokeObjectURL(a.href)}
function newVoucher(){if(!active()){alert('Primero crea o selecciona una empresa.');go('companies');return}modal('Nuevo comprobante',`<form id="voucherForm"><div class="form-grid"><label>Nº comprobante<input name="number" required value="${data.vouchers.length+1}"></label><label>Fecha<input name="date" type="date" required value="${new Date().toISOString().slice(0,10)}"></label><label class="full-field">Concepto / Glosa<input name="concept" required></label><label>Debe<input name="debit" type="number" step="0.01" min="0" required></label><label>Haber<input name="credit" type="number" step="0.01" min="0" required></label></div><div class="notice">La V1 valida que el total Debe sea igual al total Haber.</div><div class="form-actions"><button type="button" class="btn ghost" id="cancelModal">Cancelar</button><button class="btn primary">Registrar comprobante</button></div></form>`);$('#cancelModal').onclick=closeModal;$('#voucherForm').onsubmit=e=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.target));v.debit=Number(v.debit);v.credit=Number(v.credit);if(Math.abs(v.debit-v.credit)>0.005){alert('El comprobante no está cuadrado: Debe y Haber deben ser iguales.');return}v.companyId=active().id;data.vouchers.push(v);save();closeModal();go('vouchers')}}
function newUFV(){modal('Registrar UFV',`<form id="ufvForm"><div class="form-grid"><label>Fecha<input name="date" type="date" required value="${new Date().toISOString().slice(0,10)}"></label><label>Valor UFV<input name="value" type="number" step="0.000001" required></label></div><div class="form-actions"><button type="button" class="btn ghost" id="cancelModal">Cancelar</button><button class="btn primary">Guardar</button></div></form>`);$('#cancelModal').onclick=closeModal;$('#ufvForm').onsubmit=e=>{e.preventDefault();data.ufv.push(Object.fromEntries(new FormData(e.target)));save();closeModal();render()}}
function newFX(){modal('Registrar tipo de cambio',`<form id="fxForm"><div class="form-grid"><label>Fecha<input name="date" type="date" required value="${new Date().toISOString().slice(0,10)}"></label><label>Moneda<input name="currency" required placeholder="USD"></label><label>Compra<input name="buy" type="number" step="0.0001" required></label><label>Venta<input name="sell" type="number" step="0.0001" required></label></div><div class="form-actions"><button type="button" class="btn ghost" id="cancelModal">Cancelar</button><button class="btn primary">Guardar</button></div></form>`);$('#cancelModal').onclick=closeModal;$('#fxForm').onsubmit=e=>{e.preventDefault();data.fx.push(Object.fromEntries(new FormData(e.target)));save();closeModal();render()}}
$('#loginForm').onsubmit=e=>{e.preventDefault();if($('#loginUser').value==='admin'&&$('#loginPass').value==='CL&CF2026'){sessionStorage.setItem('clcf_login','1');showApp()}else $('#loginError').textContent='Usuario o contraseña incorrectos.'};$('#logoutBtn').onclick=()=>{sessionStorage.removeItem('clcf_login');location.reload()};$('#modalClose').onclick=closeModal;$('#modal').onclick=e=>{if(e.target.id==='modal')closeModal()};document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>go(b.dataset.page));$('#switchCompany').onclick=()=>go('companies');$('#menuBtn').onclick=()=>$('#sidebar').classList.toggle('open');
if(sessionStorage.getItem('clcf_login')==='1')showApp();
